### ISSUE TITLE
Compile error: undefined reference to 'runtime'

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#796]
Compile error: undefined reference to 'runtime' when trying to compile on Ubuntu 18.04:

```
sudo apt install zsync
./build.sh 
./build.sh
# sudo make install ## does not work; hence:
mkdir build/
cd build/
cmake -DUSE_SYSTEM_XZ=ON -DUSE_SYSTEM_INOTIFY_TOOLS=ON -DUSE_SYSTEM_LIBARCHIVE=ON -DUSE_SYSTEM_GTEST=OFF -DCMAKE_INSTALL_PREFIX=/usr ..
make -j$(nproc)

[ 50%] Built target xdg-basedir
[ 51%] Linking C executable appimagetool
CMakeFiles/appimagetool.dir/appimagetool.c.o: In function `main':
/home/me/AppImageUpdate/AppImageKit/src/appimagetool.c:746: undefined reference to `runtime_len'
/home/me/AppImageUpdate/AppImageKit/src/appimagetool.c:747: undefined reference to `runtime'
collect2: error: ld returned 1 exit status
src/CMakeFiles/appimagetool.dir/build.make:214: recipe for target 'src/appimagetool' failed
make[2]: *** [src/appimagetool] Error 1
CMakeFiles/Makefile2:1284: recipe for target 'src/CMakeFiles/appimagetool.dir/all' failed
make[1]: *** [src/CMakeFiles/appimagetool.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```
Line 747:

https://github.com/AppImage/AppImageKit/blob/092f90adbcf4a981d829a6e17be3586240c17a63/src/appimagetool.c#L747

I suspect this might have to do with https://github.com/AppImage/AppImageKit/commit/0afd5757f659336d5783087119d40c34a410b63b @nurupo @TheAssassin?

**Comment by nurupo** [comment]
Can you run `readelf -a` on `data.o` and give output of the `xxd -i runtime` command? It does work for me and for Travis-CI on here. I was testing on Debian Stretch docker image, not on Ubuntu 18.04 though.

>make -j$(nproc)

I see you like to live dangerously!

**Comment by probonopd** [comment]
```
me@host:~/AppImageUpdate/AppImageKit/build$ readelf -a ../build/src/data.o
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          66304 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           64 (bytes)
  Number of section headers:         5
  Section header string table index: 4

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .data             PROGBITS         0000000000000000  00000040
       00000000000101e0  0000000000000000  WA       0     0     1
  [ 2] .symtab           SYMTAB           0000000000000000  00010220
       0000000000000078  0000000000000018           3     2     8
  [ 3] .strtab           STRTAB           0000000000000000  00010298
       0000000000000040  0000000000000000           0     0     1
  [ 4] .shstrtab         STRTAB           0000000000000000  000102d8
       0000000000000021  0000000000000000           0     0     1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  l (large), p (processor specific)

There are no section groups in this file.

There are no program headers in this file.

There is no dynamic section in this file.

There are no relocations in this file.

The decoding of unwind sections for machine type Advanced Micro Devices X86-64 is not currently supported.

Symbol table '.symtab' contains 5 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 0000000000000000     0 SECTION LOCAL  DEFAULT    1 
     2: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT    1 _binary_runtime_start
     3: 00000000000101e0     0 NOTYPE  GLOBAL DEFAULT    1 _binary_runtime_end
     4: 00000000000101e0     0 NOTYPE  GLOBAL DEFAULT  ABS _binary_runtime_size

No version information found in this file.

me@host:~/AppImageUpdate/AppImageKit/build$ xxd -i ./out/runtime
(output attached)
```

[xxd.txt.zip](https://github.com/AppImage/AppImageKit/files/2057415/xxd.txt.zip)

**Comment by nurupo** [comment]
>     2: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT    1 _binary_runtime_start
>     3: 00000000000101e0     0 NOTYPE  GLOBAL DEFAULT    1 _binary_runtime_end
>     4: 00000000000101e0     0 NOTYPE  GLOBAL DEFAULT  ABS _binary_runtime_size

These symbols are wrong, they are generated by `ld`. You must be still using `data.o` generated by `ld` somehow, even though https://github.com/AppImage/AppImageKit/commit/0afd5757f659336d5783087119d40c34a410b63b removed the use of `ld`. You can even see in your xxd output that it uses `__out_runtime` names (if you didn't put `./out/` in your command invocation you'd get the `runtime_len' and `runtime`).

**Comment by probonopd** [comment]
Do you know what needs to be changed? CMake is like Chinese to me. cc @TheAssassin

**Comment by nurupo** [comment]
Grepping the repo for " runtime" revealed this:

>src/CMakeLists.txt:    COMMAND ld -r -b binary -o data.o runtime

so perhaps that's what is doing it? I haven't seen it before and it certainly needs to be changed to match the command from https://github.com/AppImage/AppImageKit/commit/0afd5757f659336d5783087119d40c34a410b63b  Can you change that to the command from the https://github.com/AppImage/AppImageKit/commit/0afd5757f659336d5783087119d40c34a410b63b commit and see if your build succeeds? You might need to do a clean build.

**Comment by probonopd** [comment]
Using

```
add_custom_command(OUTPUT data.o
    COMMAND xxd -i runtime | $CC -c -x c - -o data.o
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/runtime
)
```
getting

```
[ 51%] Generating data.o
/bin/sh: 1: C: not found
src/CMakeFiles/appimagetool.dir/build.make:61: recipe for target 'src/data.o' failed
make[2]: *** [src/data.o] Error 127
CMakeFiles/Makefile2:1284: recipe for target 'src/CMakeFiles/appimagetool.dir/all' failed
make[1]: *** [src/CMakeFiles/appimagetool.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by nurupo** [comment]
Ubuntu build succeeds for me without any changes:

```
[100%] Linking CXX executable test_getsection
cd /AppImageKit/build/tests && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_getsection.dir/link.txt --verbose=1
/usr/bin/c++  -O3 -DNDEBUG  -rdynamic CMakeFiles/test_getsection.dir/test_getsection.cpp.o CMakeFiles/test_getsection.dir/__/src/elf.c.o CMakeFiles/test_getsection.dir/__/src/getsection.c.o  -o test_getsection ../src/xdg-basedir/libxdg-basedir.a -lpthread ../squashfuse-EXTERNAL-prefix/src/squashfuse-EXTERNAL/.libs/libsquashfuse.a ../squashfuse-EXTERNAL-prefix/src/squashfuse-EXTERNAL/.libs/libsquashfuse_ll.a ../squashfuse-EXTERNAL-prefix/src/squashfuse-EXTERNAL/.libs/libfuseprivate.a -larchive -Wl,-Bstatic -llzma -Wl,-Bdynamic -lglib-2.0 -lz -lcairo /usr/local/lib/libgtest.a 
make[2]: Leaving directory '/AppImageKit/build'
[100%] Built target test_getsection
make[1]: Leaving directory '/AppImageKit/build'
/usr/bin/cmake -E cmake_progress_start /AppImageKit/build/CMakeFiles 0
```

Here is my build script (I'm building inside a Docker container):

```sh
sudo docker run --rm -it ubuntu:18.04 /bin/bash

apt-get update
apt-get install -y --no-install-recommends \
    ca-certificates \
    git-core \
    make \
    automake \
    autoconf \
    libtool \
    make \
    gcc \
    g++ \
    desktop-file-utils \
    cmake \
    patch \
    wget \
    xxd \
    patchelf \
    libfuse-dev \
    liblzma-dev \
    libglib2.0-dev \
    libssl-dev \
    libinotifytools0-dev \
    liblz4-dev \
    libcairo-dev \
    libarchive-dev \
    libgtest-dev

# liblzma-dev installs both .a and .so. Having .so breaks AppImageKit building, as it will pick .so thinking it's .a.
rm /usr/lib/${TRIPLE}/liblzma.so

# build gtest
cd /usr/src/gtest
cmake -DCMAKE_BUILD_TYPE=RELEASE .
make install
cd -

git clone --recursive https://github.com/AppImage/AppImageKit
cd AppImageKit
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RELEASE \
        -DUSE_SYSTEM_XZ=ON \
        -DUSE_SYSTEM_INOTIFY_TOOLS=ON \
        -DUSE_SYSTEM_LIBARCHIVE=ON \
        -DUSE_SYSTEM_GTEST=ON \
        ..
make VERBOSE=1 -j1
make install
```

**Comment by nurupo** [comment]
@probonopd well, yeah, there is no `$CC` variable defined in the cmake script. For a quick test you could replace it with gcc/clang. For a proper fix we need to dig cmake documentation to see which variable to use in place of `$CC`.

**Comment by nurupo** [comment]
It looks like you need to use `${CMAKE_C_COMPILER}` in place of `$CC`, i.e.

```cmake
add_custom_command(OUTPUT data.o
    COMMAND xxd -i runtime | ${CMAKE_C_COMPILER} -c -x c - -o data.o
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/runtime
)
```
